### ISSUE TITLE
How is packages.txt generated?

### ISSUE THREAD

**Issue by wildplant** [caleb531/dotfiles#1]
Dear brother,  may you have peace in Christ. 
I also use Atom, I want to know how can you create packages.txt automatically?
BTW, atom-material-ui and atom-material-syntax are awesome for me. why not take a try?

**Comment by caleb531** [comment]
Regarding syntax themes: long live [Monokai](https://atom.io/themes/monokai)! :P 

The `packages.txt` file is apart of a custom system I wrote from scratch for syncing my Atom packages (see my `init.coffee`). Every time I install package (via the Atom GUI or via the `apm` utility), my system will add that package name to `packages.txt`. Similarly, when I uninstall a package, the system removes the uninstalled package's name from `packages.txt`. Furthermore, if I install a package on one machine and commit `packages.txt`, then switch to Atom on another machine, my system will automatically install that package on the other machine when I `git pull` my dotfiles.

However, this package-syncing system of mine is growing rather unwieldy, and its complexity makes it annoying at times (for reasons I don't desire to list right now). Therefore, I am thinking of switching to a more robust system for syncing packages, possibly the [package-sync](https://atom.io/packages/package-sync) package (which I recommend for you).

**Comment by wildplant** [comment]
OK, noted, thanks 👍

**Comment by caleb531** [comment]
My pleasure, @wildplant! Also, you may be happy to know that your question here has inspired me to finally switch over to `package-sync` as my preferred system for syncing my Atom packages. You can browse [my latest commit history](https://github.com/caleb531/dotfiles/commits/master) to see what changed (if you're curious). :)
